#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: set ts=4
#
# Copyright 2023-present Linaro Limited
#
# SPDX-License-Identifier: MIT


import argparse
import logging
import os
import sys

from squad_client.core.api import SquadApi

import squadutilslib

squad_host_url = "https://qa-reports.linaro.org/"
SquadApi.configure(cache=3600, url=os.getenv("SQUAD_HOST", squad_host_url))

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def parse_args(raw_args):
    parser = argparse.ArgumentParser(
        description="Fetch an LTP TuxRun reproducer and adapt it to run a list of LTP tests."
    )

    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--project", help="The name of the SQUAD project.")
    group.add_argument(
        "--branch",
        help="The name of the Linux kernel branch. Supported branch names: {0}".format(
            ", ".join(squadutilslib.supported_branch_names())
        ),
    )

    parser.add_argument(
        "--group",
        required=True,
        help="The name of the SQUAD group.",
    )

    parser.add_argument(
        "--device-name",
        required=True,
        help="The device name (for example, qemu-arm64).",
    )

    parser.add_argument(
        "--tests",
        required=True,
        nargs="+",
        help="The list of tests to run.",
    )

    parser.add_argument(
        "--build-names",
        required=False,
        default=["gcc-12-lkftconfig"],
        nargs="+",
        help="The list of accepted build names (for example, gcc-12-lkftconfig). Regex is supported.",
    )

    parser.add_argument(
        "--suite-name",
        required=False,
        default="ltp-syscalls",
        help="The suite name to grab a reproducer for.",
    )

    parser.add_argument(
        "--allow-unfinished",
        action="store_true",
        default=False,
        help="Allow fetching of reproducers where the build is marked as unfinished.",
    )

    parser.add_argument(
        "--debug",
        action="store_true",
        default=False,
        help="Display debug messages.",
    )

    return parser.parse_args(raw_args)


def run(raw_args=None):
    args = parse_args(raw_args)

    project = None

    # If a branch name is provided, look up the project name
    if args.branch:
        try:
            project = squadutilslib.look_up_project_by_branch(args.branch)
        except Exception as e:
            logger.error(
                f"{e}\nIf branch exists but is not in the supported list, use --project to specify the project name."
            )
            return -1
    else:
        project = args.project

    try:
        tuxrun_reproducer_file = squadutilslib.find_reproducer(
            args.group,
            project,
            args.device_name,
            args.debug,
            args.build_names,
            args.suite_name,
            args.allow_unfinished,
        )
    except squadutilslib.ReproducerNotFound as e:
        logger.warning(
            f"No reproducer could be found for {args.group} {args.project} {args.device_name} {args.build_names}"
        )
        logger.warning(f"{e}")
        return -1

    reproducer = squadutilslib.create_ltp_tuxrun_reproducer(tuxrun_reproducer_file, args.suite_name, args.tests)

    print(reproducer)


if __name__ == "__main__":
    sys.exit(run())
