#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: set ts=4
#
# Copyright 2023-present Linaro Limited
#
# SPDX-License-Identifier: MIT


import argparse
import logging
import os
import pathlib
import sys

from squad_client.core.api import SquadApi

import squadutilslib

squad_host_url = "https://qa-reports.linaro.org/"
SquadApi.configure(cache=3600, url=os.getenv("SQUAD_HOST", squad_host_url))

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def parse_args(raw_args):
    parser = argparse.ArgumentParser(
        description="Get a TuxRun reproducer for a given group, project, device and suite."
        + " Optionally update the TuxRun reproducer to run custom commands and/or run in the cloud with TuxPlan."
    )

    parser.add_argument(
        "--group",
        required=True,
        help="The name of the SQUAD group.",
    )

    parser.add_argument(
        "--project",
        required=True,
        help="The name of the SQUAD project.",
    )

    parser.add_argument(
        "--device-name",
        required=True,
        help="The device name (for example, qemu-arm64).",
    )

    parser.add_argument(
        "--build-names",
        required=False,
        default=["gcc-12-lkftconfig"],
        nargs="+",
        help="The list of accepted build names (for example, gcc-12-lkftconfig). Regex is supported.",
    )
    parser.add_argument(
        "--suite-name",
        required=False,
        default="ltp-syscalls",
        help="The suite name to grab a reproducer for.",
    )

    parser.add_argument(
        "--allow-unfinished",
        action="store_true",
        default=False,
        help="Allow fetching of reproducers where the build is marked as unfinished.",
    )

    subparsers = parser.add_subparsers(
        dest="update", required=True, help="Update TuxRun reproducers to run custom commands in TuxRun or TuxPlan."
    )
    parser_updates = subparsers.add_parser("update")
    parser_updates.add_argument(
        "--local",
        action="store_true",
        default=False,
        help="Create a TuxRun reproducer when updating rather than a TuxPlan.",
    )

    group = parser_updates.add_mutually_exclusive_group(required="update" in sys.argv)
    group.add_argument("--ltp-tests", help="A list of LTP tests to run.", nargs="+")
    group.add_argument("--custom-command", help="A custom command to add to the reproducer")

    parser.add_argument(
        "--debug",
        action="store_true",
        default=False,
        help="Display debug messages.",
    )

    return parser.parse_args(raw_args)


def run(raw_args=None):
    args = parse_args(raw_args)

    try:
        tuxrun_reproducer_file = squadutilslib.find_reproducer(
            args.group,
            args.project,
            args.device_name,
            args.debug,
            args.build_names,
            args.suite_name,
            args.allow_unfinished,
        )
        reproducer_txt = pathlib.Path(tuxrun_reproducer_file).read_text(encoding="utf-8")
        print(reproducer_txt)
    except squadutilslib.ReproducerNotFound as e:
        logger.warning(
            f"No reproducer could be found for {args.group} {args.project} {args.device_name} {args.build_names}"
        )
        logger.warning(f"{e}")
        return -1
    if args.update:
        if args.ltp_tests:
            custom_command = squadutilslib.create_ltp_custom_command(tests=args.ltp_tests)
        else:
            custom_command = args.custom_command

        if args.local:
            reproducer = squadutilslib.create_ltp_tuxrun_reproducer(
                tuxrun_reproducer_file, args.suite_name, custom_command
            )
        else:
            reproducer = squadutilslib.create_ltp_tuxsuite_plan_reproducer(tuxrun_reproducer_file, custom_command)

        print(reproducer)


if __name__ == "__main__":
    sys.exit(run())
